#Informations de connexion database
version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test42
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  music.api:
    build: .
    ports:
      - 8080:80